### PR TITLE
fix crash when using sphinx > 1.3.4

### PR DESCRIPTION
**Pull request by mindw**
Probably caused by:
sphinx-doc/sphinx@6dc7ca0234638436f3decfb85990613e69f7809f

### CODE REVIEW

**Comment by mindw** [comment]
BTW tests cannot be run on windows.

**Comment by bitprophet** [comment]
Thanks! Weird tho, I don't get why adding a line setter fixes a crash caused by a patch that only seems to get. Will try reproducing locally in a sec regardless.

**Comment by bitprophet** [comment]
Hrm, under Sphinx 1.4.1 I can't repro this with one of my project sites (specifically, `www` here: https://github.com/paramiko/paramiko/tree/master/sites).

Can you provide more details on how you're getting the crash? Specific sphinx and/or python version, which docs repo you're building, etc. Thanks!

**Comment by bitprophet** [comment]
Hrm, well *now* I'm able to reproduce it, originally via travis (https://travis-ci.org/bitprophet/releases/jobs/126233623#L336) but then when I re-upgrade to Sphinx 1.4.1 (I had gone back to 1.3 for funsies after the above) it's happening to me locally as well. Good ol' heisenbugs.

**Comment by bitprophet** [comment]
P.S. @mindw if you can file another ticket about the test suite & Windows I'd like to have that tracked too, I don't know offhand what we're doing that's Unix specific (probably something file related?). thanks!

**Comment by mindw** [comment]
OK, will do.

**Comment by bitprophet** [comment]
Also, stating for the record here that this bug was probably my fault, I think the issue is that `line` is accidentally shadowing a member on a parent class (`node.Element` or above) and either it didn't exist prior to Sphinx 1.4, or it existed but wasn't actually triggering an exception until then.

Going to rename that method soon anyways for #45 probably. Anyway. Merged now regardless :)

**Comment by mindw** [comment]
Probably caused by:
sphinx-doc/sphinx@6dc7ca0234638436f3decfb85990613e69f7809f

**Pull request merged**
