### PR TITLE
Support Sphinx 1.7

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/bitprophet/releases/issues/73

### CODE REVIEW

**Comment by hroncok** [comment]
The integration tests fail. I only run unittests. Will try to fix.

**Comment by hroncok** [comment]
BTW I've tested this locally with Python 3.70rc1. You might want to add it to the CI, but that's out of scope of this PR.

**Comment by bitprophet** [comment]
Awesome, thanks! I'll take this for a spin soon.

**Comment by bitprophet** [comment]
- My current default venvs are Python 3.6, fwiw...
- checked out our 1.5 branch since this is largely a bugfix level change
- triple checked that Sphinx 1.7.5 blows up when I run `inv test`
- cherry-picked the commit from this PR
- confirmed that `inv test` works fine now
- merged up to 1.6 and master
- retested
- just pushed for Travis checkup

**Comment by hroncok** [comment]
Merged in b4255449fd831443b739ff01653685999bdcd4c7

**Comment by bitprophet** [comment]
Beat me to it! Was gonna wait til Travis was green :D so far, 1.6 has checked in so I'm not worried.

**Pull request closed without merging**
