### PR TITLE
Support for tags with prefix (rebased)

### PR DESCRIPTION
**Pull request by tony**
Rebased version of #54 by @scolby33

I'm not fully sure if scolby gets full credit if I rebase and make a PR. @scolby you're free to use this rebase in your own branch/PR if you'd like. I need this feature on several projects, because they all have broken links at the moment.

See also: #65

### CODE REVIEW

**Comment by tony** [comment]
@bitprophet In 'Next releases' URL:

With this PR: https://libtmux.git-pull.com/en/latest/history.html
Without: https://cihai.git-pull.com/en/latest/history.html

**Comment by scolby33** [comment]
Thanks @tony for the update on this. I have done rebases on pull requests before and I think the commit authorship is saved, unless you squash everything(?). Either way, I'm not too concerned about the credit and am happy that my contributions were useful!

**Comment by tony** [comment]
@scolby33 @bitprophet Rebased against 8c01876

**Comment by tony** [comment]
@bitprophet How about now?

**Comment by tony** [comment]
Sorry this is stale, someone else is okay to carry on the torch - I don't use this package anymore (just prefer plain files now)

I will close this, but keep my branch up in case anyone wants to continue

**Pull request closed without merging**
